import {createSlice} from "@reduxjs/toolkit";

interface Rq {
    img:string,
    tit:string
}
export interface AppContent {
    title:string,
    link?:string,
    tel?:string,
    rq?:[Rq,Rq] ,
    companyId:number,
    tags?:Array<number>
}
export const apps:Array<AppContent>=[
    {
        title:'车轮滚滚',
        link:'https://www.clgg.com',
        tel:'400-888-1122',
        companyId:1,
        tags:[1]
    }
    ,{
        title:'远行供应链官网',
        link:'http://yuanxinggroup.com/',
        tel:'400-888-1122',
        companyId:2,
        tags:[1]
    },{
        title:'远行销售管理系统',
        link:'http://ts.clgg.com:81/',
        companyId:2,
        tags:[2]
    }
    ,{
        title:'贴心天行健',
        link:'http://www.sqtxj.com/',
        companyId:3,
        tel:'400-880-9818-4',
        tags:[1]
    },{
        title:'天行健车队管理系统',
        link:'http://www.sqtxj.com:10086/',
        companyId:3,
        tel:'400-880-9818-4',
        tags:[4]
    }
    ,{
        title:'天行健智能业务运营管理系统',
        link:'http://www.sqtxj.com:10088/login',
        companyId:3,
        tel:'400-880-9818-4',
        tags:[4]
    }
    ,{
        title:'天行健车贷管理系统',
        link:'http://www.sqtxj.com:50188/',
        companyId:3,
        tel:'400-880-9818-4',
        tags:[4]
    }
    ,{
        title:'天行健渣土车运营监管系统',
        link:'http://www.txjpt.com:10010/ztcweb/html/login/login.html',
        companyId:3,
        tel:'400-880-9818-4',
        tags:[4]
    }
    ,{
        title:'陕汽控股',
        link:'http://www.sxqc.com',
        companyId:7,
        tags:[1]
    }
    ,{
        title:'陕汽商用车',
        link:'http://www.hsqc.com.cn/',
        companyId:7,
        tags:[1]
    }
    ,{
        title:'德银融资租赁官网',
        link:'https://www.deewinfl.com/',
        tel:'021-61762588',
        companyId:4,
        tags:[1]
    }
    ,{
        title:'德银融资租赁系统',
        link:'http://www.deewinfl.cn/',
        tel:'021-61762588',
        companyId:4,
        tags:[2]
    }
    ,{
        title:'档案系统',
        link:'http://218.97.55.27',
        tel:'021-61762588',
        companyId:4,
        tags:[2]
    }
    ,{
        title:'美信保险经纪',
        link:'http://www.meixinsh.com/',
        tel:'021-52416660',
        companyId:5,
        tags:[1]
    }
    ,{
        title:'博云车联',
        link:'http://www.car900.com',
        companyId:2,
        tags:[2,4]
    }
    ,{
        title:'智慧车队管理系统',
        link:'http://115.236.59.234:8080',
        companyId:2,
        tags:[2,4]
    }
    ,{
        title:'智能车队管理系统',
        link:'https://cz.clgg.com',
        companyId:2,
        tags:[2]
    }
    ,{
        title:'保理业务系统',
        link:'http://factoring.deewinkg.com:8888',
        tel:'（86-10）84486758',
        companyId:6,
        tags:[2]
    }
    ,{
        title:'通汇官网',
        link:'http://www.sxtonghui.com',
        companyId:9,
        tags:[1]
    }
    ,{
        title:'通汇综合服务平台',
        link:'http://www.sxtonghui.com:6080/kccx/',
        companyId:9,
        tags:[2]
    }
    ,{
        title:'车轮滚滚移动端',
        rq:[
            {
                img:'http://www.clgg.com:9838/upload/driverCircle/202012/30/3e67513b51904939b5f290ed2fba3429.png',
                tit:'安卓'
            },
            {
                img:'http://www.clgg.com:9838/upload/driverCircle/202012/30/138b5200e42d4280803d5c3a0db56fa7.png',
                tit:'IOS'
            }
        ],
        companyId:1,
        tags:[3]
    }
];


const appsSlice=createSlice({
    name:'apps',
    initialState:apps,
    reducers:{
        ' ':(state)=>{}
    },
})

export default appsSlice.reducer;